[package]
name = "gu-hardware"
version = "0.1.0"

[dependencies]
gu-actix= { path="../gu-actix" }
gu-base= { path="../gu-base" }
gu-p2p= { path="../gu-p2p" }

sysinfo = "0.5"
log = "0.4"
actix = "0.7"
error-chain = "0.12"
futures = "0.1"
clap = "2.32"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
actix-web = "0.7"