[package]
publish=false
name = "gu-hub"
version = "0.1.0"
build = "build.rs"
license = "MIT"
authors=["golemfactory"]

[dependencies]
gu-base= { path="../gu-base" }
gu-p2p= { path="../gu-p2p" }
gu-persist = { path = "../gu-persist" }
gu-actix = { path = "../gu-actix" }
gu-lan = { path = "../gu-lan" }
gu-hardware = { path = "../gu-hardware" }
gu-event-bus = { path = "../gu-event-bus" }


clap = "2.32"
log="0.4"
env_logger = "0.5"
tokio-uds = "0.2"

serde = "1.0"
serde_derive = "1.0"
serde_json="1.0"

error-chain = "0.12"
failure="0.1"

futures = "0.1"
tokio="0.1"
directories="1.0"
rand="0.5"
flate2 = { version = "1.0", features = ["rust_backend"], default-features = false }
semver = { version = "0.9", features = ["serde"] }
zip = "0.4"

actix = "0.7"
actix-web = {version= "0.7"}
bytes = "0.4.10"

mdns = { git = "https://github.com/plietar/rust-mdns", rev = "0974ab4f" }

prettytable-rs="0.7"

[build-dependencies]
flate2 = { version = "1.0", features = ["rust_backend"], default-features = false }


[package.metadata.deb]
assets=[
    ["webapp/ui-bootstrap-tpls-2.5.0.min.js", "usr/lib/golemu/webapp/","644"],
    ["webapp/icons/unlimited-logo.svg","usr/lib/golemu/webapp/icons/","644"],
    ["webapp/icons/unlimited-logo-b&w.svg","usr/lib/golemu/webapp/icons/","644"],
    ["webapp/icons/providers.svg","usr/lib/golemu/webapp/icons/","644"],
    ["webapp/icons/status.svg","usr/lib/golemu/webapp/icons/","644"],
    ["webapp/icons/refresh.svg","usr/lib/golemu/webapp/icons/","644"],
    ["webapp/icons/rendering.svg","usr/lib/golemu/webapp/icons/","644"],
    ["webapp/providers.html","usr/lib/golemu/webapp/","644"],
    ["webapp/status.html","usr/lib/golemu/webapp/","644"],
    ["webapp/modal-confirm.html","usr/lib/golemu/webapp/","644"],
    ["webapp/index.html","usr/lib/golemu/webapp/","644"],
    ["webapp/hdsession.html","usr/lib/golemu/webapp/","644"],
    ["webapp/app.js","usr/lib/golemu/webapp/","644"],
    ["target/release/gu-hub", "usr/bin/", "755"],
    ["deployment/gu-hub.service", "lib/systemd/system/", "644"],

]