[package]
publish=false
name = "gu-hub"
version = "0.1.0"
build = "build.rs"

[dependencies]
gu-base= { path="../gu-base" }
gu-p2p= { path="../gu-p2p" }
gu-persist = { path = "../gu-persist" }
gu-actix = { path = "../gu-actix" }
gu-lan = { path = "../gu-lan" }
gu-hardware = { path = "../gu-hardware" }


clap = "2.32"
log="0.4"
env_logger = "0.5"
tokio-uds = "0.2"

serde = "1.0"
serde_derive = "1.0"
serde_json="1.0"

error-chain = "0.12"
failure="0.1"

futures = "0.1"
tokio="0.1"
directories="1.0"
rand="0.5"
flate2 = { version = "1.0", features = ["rust_backend"], default-features = false }

actix = "0.7"
actix-web = {version= "0.7", features=["tls"]}

mdns = { git = "https://github.com/plietar/rust-mdns", rev = "0974ab4f" }

prettytable-rs="0.7"

[dev-dependencies]
flate2 = { version = "1.0", features = ["rust_backend"], default-features = false }