[package]
name = "gu-webapp"
version = "0.1.0"
authors = ["Przemysław K. Rekucki <przemyslaw.rekucki@golem.network>"]

[dependencies]
sha1="0.6"
flate2 = { version = "1.0", features = ["rust_backend"], default-features = false }
actix = "0.7"
actix-web = {version= "0.7"}
