[workspace]


members= [
    'ethkey',
    'gu-actix',
    'gu-base',
    'gu-webapp',
    'gu-provider',
    'gu-hub',
    'gu-net',
    'gu-persist',
    'gu-lan',
    'gu-hardware',
    'gu-event-bus',
    'gu-model',
    'gu-client',
    'gu-hdman',
]

[profile.release]
codegen-units = 1
lto=true


[patch.crates-io]
#actix-web = { git = "https://github.com/prekucki/actix-web.git", default-features=false }
#ring = { git="https://github.com/briansmith/ring.git", tag="0.12.1" }
#untrusted = {git="https://github.com/briansmith/untrusted.git", tag="0.5.1" }


