[workspace]

members= [
    'gu-actix',
    'gu-base',
    'gu-webapp',
	'gu-provider',
	'gu-hub',
	'gu-ethkey',
	'gu-p2p',
	'gu-persist',
	'gu-lan',
	'gu-hardware',
]

[dependencies]
log="0.4"
flate2 = { version = "1.0", features = ["rust_backend"], default-features = false }

#[patch.'https://github.com/tworec/parity-ethereum']
#ethkey = { path = '../parity-ethereum/ethkey'}
#ethstore = { path = '../parity-ethereum/ethstore'}

[patch.'https://github.com/paritytech/parity-common']
parity-crypto = { git = 'https://github.com/tworec/parity-common', branch='ring-v-upgrade'}
#parity-crypto = { path = '../parity-common/parity-crypto'}

[profile.release]
codegen-units = 1
lto=true
