[workspace]

members= [
	'gu-provider',
	'gu-hub',
	'gu-ethkey',
	'gu-p2p',
	'gu-persist',
	'gu-lan',
]

[dependencies]
log="0.4"

[patch.'https://github.com/tworec/parity-ethereum']
ethkey = { path = '../parity-ethereum/ethkey'}
ethstore = { path = '../parity-ethereum/ethstore'}