[workspace]

members= [
    'gu-actix',
    'gu-base',
    'gu-webapp',
    'gu-provider',
    'gu-hub',
    'gu-ethkey',
    'gu-net',
    'gu-persist',
    'gu-lan',
    'gu-hardware',
    'gu-event-bus',
    'gu-model',
    'gu-client',
]

[profile.release]
codegen-units = 1
lto=true
