swagger: "2.0"
info:
  title: Golem unlimited low level hub API
  description: API description in Markdown.
  version: 1.0.0
schemes:
  - https
paths:
  /peer:
    get:
      summary: Returns a list hub peers.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/PeerInfo'
  /sessions
    get:
      
definitions:
  PeerInfo:
    description: "General information about GU subnetwork node"
    required:
      - nodeId
      - peerAddr
    properties:
      nodeName:
        type: string
        description: "Node name or hostname from reverse dns if node name is not set"
      peerAddr:
        type: string
        description: "node address from current connection formated as <ip-addr>:<port>"
      nodeId:
        type: string
        description: "node public key hash in etherium format"
        example: 0x875f272d3b9e7b55a5784a131a60bf3d7a42c73c
        readOnly: true
      tags:
        type: array
        items:
          type: string

