[package]
name = "gu-model"
version = "0.1.0"
authors = ["Golem Factory"]

[dependencies]
actix = "0.7"
actix-web = {version= "0.7", default-features=false}
serde_derive = "1.0"
serde_json="1.0"
serde = "1.0.80"
gu-net = { path = "../gu-net" }
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
