[package]
name = "gu-lan"
version = "0.1.0"
authors = ["Hubert Banaszewski <hubert.banaszewski@golem.network>"]

[dependencies]
actix = "0.7"
bytes = "0.4"
dns-parser = "0.8"
env_logger = "0.5"
error-chain = "0.12"
futures = "0.1"
log = "0.4"
#socket2 = "0.3"
socket2 = { version = "0.3", features = ["reuseport"] }
tokio = "0.1"
tokio-codec = "0.1"