[package]
name = "gu-provider"
version = "0.1.1"

[dependencies]
futures="0.1"
tokio-io="0.1"
actix = "0.7"
actix-web = {version= "0.7", features = ["rust-tls"]}

serde = "1.0"
serde_derive = "1.0"
serde_json="1.0"

log = "0.4"
env_logger = "0.5"
clap = "2.32"
tokio="0.1"
directories="1.0"
error-chain = "0.12"
tokio-uds = "0.2"
rand = "0.5"
uuid = { version = "0.7", features = ["v4"] }
bytes = "0.4"
flate2 = { version = "1.0", features = ["rust_backend"], default-features = false }
tar = "0.4"

mdns = { git = "https://github.com/plietar/rust-mdns", rev = "0974ab4f" }

gu-base= { path="../gu-base" }
gu-actix = { path = "../gu-actix" }
gu-p2p = { path = "../gu-p2p" }
gu-persist = { path = "../gu-persist" }
gu-lan = { path = "../gu-lan"}
gu-ethkey = { path = "../gu-ethkey"}

[target.'cfg(target_os = "linux")'.dependencies]
gu-hardware = { path = "../gu-hardware"}

[target.'cfg(target_os = "macos")'.dependencies]
gu-hardware = { path = "../gu-hardware", features=["clinfo"]}