[package]
name = "gu-provider"
version = "0.1.0"

[dependencies]
futures="0.1"
tokio-io="0.1"
actix = "0.7"
actix-web = "0.7"

serde = "1.0"
serde_derive = "1.0"
serde_json="1.0"

log = "0.4"
env_logger = "0.5"
clap = "2.32"
tokio="0.1"
directories="1.0"
error-chain = "0.12"
tokio-uds = "0.2"

gu-actix = { path = "../gu-actix" }
gu-p2p = { path = "../gu-p2p" }
gu-persist = { path = "../gu-persist" }

