[package]
name = "gu-persist"
version = "0.1.0"

[dependencies]
log="0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json="1.0"
error-chain = "0.12"
futures = "0.1"
directories="1.0"

actix = "0.7"
actix_derive = "0.3"
actix-web = "0.7"

kv="0.6"
tokio-fs="0.1"
tokio-io="0.1"

gu-actix= { path="../gu-actix" }
gu-base= { path="../gu-base" }

[dev-dependencies]
clap = "2.32"
env_logger = "0.5"